services:
  postgres_db:
    image: postgres:15-alpine
    container_name: agroai_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo1:
    image: mongo:7.0
    container_name: agroai-mongo-primary
    command: ["--replSet", "agroai-rs", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27018:27017"
    volumes:
      - mongo1_data:/data/db
    restart: always

  mongo2:
    image: mongo:7.0
    container_name: agroai-mongo-sec-1
    command: ["--replSet", "agroai-rs", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27019:27017"
    volumes:
      - mongo2_data:/data/db
    restart: always

  mongo3:
    image: mongo:7.0
    container_name: agroai-mongo-sec-2
    command: ["--replSet", "agroai-rs", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27020:27017"
    volumes:
      - mongo3_data:/data/db
    restart: always

  core-service:
    build: ./core-service
    ports:
      - "3000:3000"
    env_file:
      - ./core-service/.env # 🟢 Docker leerá todo lo que esté en ese archivo
    depends_on:
      - postgres_db
      - forensic-service

  forensic-service:
    build: ./forensic-service
    ports:
      - "4000:4000"
    env_file:
      - ./forensic-service/.env
    depends_on:
      - mongo1
  
  weather-service:
    build: 
      context: ./weather-service
      dockerfile: Dockerfile
    container_name: weather-service
    env_file:
      - ./weather-service/.env
    ports:
      - "4001:4001"
    restart: unless-stopped

volumes:
  postgres_data:
  mongo1_data:
  mongo2_data:
  mongo3_data: